[package]
name = "matrix-echo-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
color-eyre = "0.6.5"
eyre = "0.6.12"
matrix-sdk = { version = "0.16.0", default-features = false, features = ["automatic-room-key-forwarding", "e2e-encryption", "socks", "sqlite"] }
matrixbot-ezlogin = { version = "0.3.9", default-features = false }
ruma-events = { version = "0.32.1", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.2", features = ["full"] }
tokio-util = "0.7.18"
toml = "1.1.2"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[features]
default = ["native-tls"]
allow-looping = []
bundled-sqlite = ["matrix-sdk/bundled-sqlite", "matrixbot-ezlogin/bundled-sqlite"]
native-tls = ["matrix-sdk/native-tls", "matrixbot-ezlogin/native-tls"]
rustls-tls = ["matrix-sdk/rustls-tls", "matrixbot-ezlogin/rustls-tls"]
unstable-msc4295 = ["ruma-events/unstable-msc4295"]

[patch.crates-io]
ruma-common = { path = "./vendor/ruma/crates/ruma-common" }
ruma-events = { path = "./vendor/ruma/crates/ruma-events" }
ruma-macros = { path = "./vendor/ruma/crates/ruma-macros" }
ruma-identifiers-validation = { path = "./vendor/ruma/crates/ruma-identifiers-validation" }
matrix-sdk = { path = "./vendor/matrix-rust-sdk/crates/matrix-sdk" }
matrix-sdk-base = { path = "./vendor/matrix-rust-sdk/crates/matrix-sdk-base" }
matrix-sdk-common = { path = "./vendor/matrix-rust-sdk/crates/matrix-sdk-common" }
matrix-sdk-crypto = { path = "./vendor/matrix-rust-sdk/crates/matrix-sdk-crypto" }
matrix-sdk-sqlite = { path = "./vendor/matrix-rust-sdk/crates/matrix-sdk-sqlite" }
matrix-sdk-store-encryption = { path = "./vendor/matrix-rust-sdk/crates/matrix-sdk-store-encryption" }
